### ISSUE TITLE
Setup for Hybrid Cloud Deployment

### ISSUE THREAD

**Issue by karthimohan** [burrsutter/9stepsawesome#24]
Hi Burr,

Great Presentation with in-depth details. That was a cool Demo. I am from the OPS team I would like to know more about the Hybrid Cloud Deployment. Does the setup include Opshift deployment on all 3 clouds and used Kubefed for federated setup. Could you please provide more details on that. Would be really helpful

**Comment by karthimohan** [comment]
@burrsutter Appreciate your response :)

**Comment by burrsutter** [comment]
@karthimohan I apologize, I have some many input channels that I forget to look at these issues.  Concerning the Hybrid Code demo that code is here: https://github.com/burrsutter/demo2-amq
You just need to have 3 OpenShift's running - ideally at Azure, Google and Amazon.  I just use try.openshift.com and launch those 3 clouds.  The try.openshift.com setup can be tricky IF you are limited experience with each cloud in question.  Start with your personal favorite and get through its learning curve before taking on another.
