### ISSUE TITLE
hello-minikube image k8s.gcr.io/echoserver:1.10 fails on minishift

### ISSUE THREAD

**Issue by lance** [burrsutter/9stepsawesome#3]
Following the steps in the [installation and getting started doc](https://github.com/burrsutter/9stepsawesome/blob/master/1_installation_started.adoc) produces the following errors in the pod's log messages when running `kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.10 --port=8080`.

```log

Generating self-signed cert
--
  | mkdir: cannot create directory '/certs': Permission denied
  | Generating a 2048 bit RSA private key
  | ..................................................+++
  | ...............................+++
  | unable to write 'random state'
  | writing new private key to '/certs/privateKey.key'
  | /certs/privateKey.key: No such file or directory
  | 140052491175576:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('/certs/privateKey.key','w')
  | 140052491175576:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
  | Starting nginx
  | 2018/08/10 19:57:39 [emerg] 8#8: BIO_new_file("/certs/certificate.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/certs/certificate.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
  | nginx: [emerg] BIO_new_file("/certs/certificate.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/certs/certificate.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)

```

The minishift and oc versions.

```sh
~ minishift version
minishift v1.22.0+7163416
~ oc version
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://192.168.99.100:8443
kubernetes v1.10.0
```

**Comment by burrsutter** [comment]
Thanks! Interesting that the error is around the certificate.  I can come up with a better "test" image for kubectl run that works better in minikube and minishift

**Comment by praveenkumar** [comment]
@burrsutter we didn't try out ourself to do that kind of deployment but will try and put the comment back to this issue.

+ @minishift/minishift-dev

**Comment by lance** [comment]
@praveenkumar thank for helping with this. Could this be done during the Create VM section where the `admin-user` addon is enabled? https://github.com/burrsutter/9stepsawesome/blob/master/1_installation_started.adoc

**Comment by lance** [comment]
@burrsutter it seems that [this](https://github.com/burrsutter/9stepsawesome/commit/e7414a48b4106276cfda6fcb3566d604eca60a70) should close this issue. Correct?
