### ISSUE TITLE
Missing 'service' from delete statement

### ISSUE THREAD

**Issue by 4everinbeta** [burrsutter/9stepsawesome#30]
On the [Step 2](https://github.com/burrsutter/9stepsawesome/blob/master/2_building_running.adoc) doc at Services>Clean Up you forgot to add the resource type that is being deleted.

$ kubectl delete **service** the-service

Otherwise you get the following error:

`error: resource(s) were provided, but no name, label selector, or --all flag specified`

**Comment by pigorv** [comment]
Was fixed in #29

**Comment by burrsutter** [comment]
Thank you
